@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!include DEVICONS/java.puml
!include DEVICONS/postgresql.puml
!include DEVICONS2/react_original.puml
!include DEVICONS2/kotlin.puml
!include FONTAWESOME/users.puml

LAYOUT_WITH_LEGEND()

'skinparam linetype ortho

title C4 Container Diagram - InsureTech (AS-IS)

Person(client, "Клиент", "Клиент системы InsureTech", $sprite="users")

System_Boundary(insuretech, "InsureTech") {

    Container(web_app, "InsecureTechWeb", "Javascript, React", "Веб-приложение InsecureTech", $sprite="react_original")

    Container(client_info, "client-info", "Kotlin, SpringBoot", "Сервис для учета клиентских данных", $sprite="kotlin")

    ContainerDb(client_info_db, "client-info-db", "PostgreSQL", "БД для хранения данных клиентов: ФИО, телефон, паспорт", $sprite="postgresql")

    Container(core_app, "core-app", "Kotlin", "Монолитное приложение:\n• отображает данные о доступных страховых продуктах\n• оформляет новые страховки\n• отображает информацию о купленных страховках", $sprite="kotlin")

    Container(ins_product_aggregator, "ins-product-aggregator", "Kotlin, SpringBoot", "Сервис для интеграции со страховыми компаниями с целью получения информации по страховым продуктам. Предоставляет единый API для core-app", $sprite="kotlin")

    ContainerDb(core_db, "core-db", "PostgreSQL", "БД используется для хранения тарифов страховых компаний, а также заявок клиентов на страховые продукты", $sprite="postgresql")

    Container(ins_comp_settlement, "ins-comp-settlement", "Kotlin, SpringBoot", "Сервис для осуществления взаиморасчётов со страховыми компаниями", $sprite="kotlin")

    ContainerDb(ins_comp_settlement_db, "ins-comp-settlement-db", "PostgreSQL", "БД используется для хранения данных об оформленных страховках и условиях взаиморасчётов с клиентами", $sprite="postgresql")
}

System_Ext(insurance_systems, "Системы страховых компаний", "Предоставляют API для получения актуальных тарифов, андерайтинга и оформления страховых продуктов")

System_Ext(partner_systems, "Системы партнёров", "Системы партнёров, интегрирующие страховые услуги в свои продукты")

System_Ext(payment_service, "Платёжный сервис", "Внешний платёжный сервис, через который осуществляется оплата страховок. Деньги уходят на счета страховых компаний")

' === Связи ===

' Клиент
Rel(client, web_app, "Использует")

' InsureTech Web
Rel(web_app, core_app, "1. Получение тарифов\n2. Создание заявок на страховки", "REST")
Rel(web_app, client_info, "Получение/сохранение информации о клиентах", "REST")
Rel(web_app, payment_service, "Проведение оплаты за страховки (redirect)", "HTTP")

' core-app
Rel(core_app, core_db, "Работа с данными", "TCP")
Rel(core_app, ins_product_aggregator, "Получение информации по продуктам и тарифам", "REST")
Rel(core_app, client_info, "Получение/сохранение информации о клиентах", "REST")
Rel(core_app, payment_service, "Проведение оплаты за страховки", "HTTP")

' ins-product-aggregator
Rel(ins_product_aggregator, insurance_systems, "Получение информации по продуктам и тарифам", "REST / SOAP / GraphQL")

' ins-comp-settlement
Rel(ins_comp_settlement, ins_comp_settlement_db, "Работа с данными", "TCP")
Rel(ins_comp_settlement, insurance_systems, "Передача данных для взаиморасчётов", "REST / SOAP / GraphQL")
Rel(ins_comp_settlement, ins_product_aggregator, "Получение информации по продуктам и тарифам", "REST")
Rel(ins_comp_settlement, core_app, "Получение информации об оформленных страховках", "REST")

' client-info
Rel(client_info, client_info_db, "Работа с данными", "TCP")

' Внешние системы
Rel(partner_systems, core_app, "Оформление страховок", "REST")

@enduml
